version: '3.5'

services:
  nuxtjs:
    build: .
    volumes:
      - '.:/usr/src/nuxt-app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0